version: 0.2 
phases: 
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  pre_build: 
    commands: 
      - $(aws ecr get-login --no-include-email) 
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" 
      - REPOSITORY_URI=130994109741.dkr.ecr.eu-west-1.amazonaws.com/hyper-bank
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}" 
      - echo $IMAGE_URI 
  build: 
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - docker build -t "$IMAGE_URI" . 
  post_build: 
    commands: 
      - docker push "$IMAGE_URI" 
      - printf '[{"name":"hyper-bank-container","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json 
artifacts: 
  files: imagedefinitions.json 